
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 34;
  public static final int FLOAT_LIT = 57;
  public static final int FORALL = 50;
  public static final int SEQ = 9;
  public static final int DIVIDE = 24;
  public static final int FUNCTION = 12;
  public static final int LBRACKET = 61;
  public static final int POWER = 25;
  public static final int CHAR = 2;
  public static final int CONCAT = 28;
  public static final int INTEGER = 55;
  public static final int LPAREN = 59;
  public static final int INT = 4;
  public static final int MINUS = 22;
  public static final int RPAREN = 60;
  public static final int CHARACTER = 53;
  public static final int SEMICOLON = 66;
  public static final int NOT = 18;
  public static final int AND = 19;
  public static final int ELSEIF = 45;
  public static final int RATIONAL = 56;
  public static final int LESSTHAN = 32;
  public static final int IN = 27;
  public static final int OR = 20;
  public static final int TDEF = 14;
  public static final int COMMA = 64;
  public static final int BOOL = 3;
  public static final int FI = 43;
  public static final int THREAD = 11;
  public static final int RAT = 5;
  public static final int PLUS = 21;
  public static final int IF = 41;
  public static final int ASSIGN = 38;
  public static final int MAIN = 17;
  public static final int DOT = 63;
  public static final int BOOLEAN = 54;
  public static final int EOF = 0;
  public static final int RETURN = 51;
  public static final int OD = 48;
  public static final int RBRACKET = 62;
  public static final int error = 1;
  public static final int LCURLY = 67;
  public static final int INTERSECTION = 30;
  public static final int EQEQ = 36;
  public static final int BREAK = 49;
  public static final int FDEF = 16;
  public static final int RCURLY = 68;
  public static final int TOP = 7;
  public static final int TIMES = 23;
  public static final int COLON = 65;
  public static final int UNION = 29;
  public static final int ELSE = 44;
  public static final int DICT = 8;
  public static final int READ = 39;
  public static final int DIFFERENCE = 31;
  public static final int WHILE = 46;
  public static final int LESSTHANEQ = 33;
  public static final int FLOAT = 6;
  public static final int THEN = 42;
  public static final int LEN = 26;
  public static final int STRING = 13;
  public static final int ALIAS = 15;
  public static final int GREATERTHANEQ = 35;
  public static final int STRING_LIT = 58;
  public static final int DO = 47;
  public static final int PRINT = 40;
  public static final int NOTEQ = 37;
  public static final int SET = 10;
  public static final int IDENTIFIER = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CHAR",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "TOP",
  "DICT",
  "SEQ",
  "SET",
  "THREAD",
  "FUNCTION",
  "STRING",
  "TDEF",
  "ALIAS",
  "FDEF",
  "MAIN",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "POWER",
  "LEN",
  "IN",
  "CONCAT",
  "UNION",
  "INTERSECTION",
  "DIFFERENCE",
  "LESSTHAN",
  "LESSTHANEQ",
  "GREATERTHAN",
  "GREATERTHANEQ",
  "EQEQ",
  "NOTEQ",
  "ASSIGN",
  "READ",
  "PRINT",
  "IF",
  "THEN",
  "FI",
  "ELSE",
  "ELSEIF",
  "WHILE",
  "DO",
  "OD",
  "BREAK",
  "FORALL",
  "RETURN",
  "IDENTIFIER",
  "CHARACTER",
  "BOOLEAN",
  "INTEGER",
  "RATIONAL",
  "FLOAT_LIT",
  "STRING_LIT",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "COMMA",
  "COLON",
  "SEMICOLON",
  "LCURLY",
  "RCURLY"
  };
}

